#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# NOTE:
# min_runs_between_change_points: units for this variable is number of runs.
# So if a test runs 2 times a day, and we want to look for sibling change point in
# the runs that happened 3 days before and after the change point,
# then this value will should be 3 * 2 = 6.

# change_point_to_recent_run_window: same units as min_runs_between_change_points.

test_1:
  test_name: apache_beam.testing.benchmarks.inference.pytorch_image_classification_benchmarks
  source: big_query
  metrics_dataset: beam_run_inference
  metrics_table: torch_inference_imagenet_results_resnet152
  project: apache-beam-testing
  metric_name: mean_load_model_latency_milli_secs
  labels:
    - perf-alert
    - run-inference
  min_runs_between_change_points: 5
  # the test runs once per day. So alert only if a perf regression lies
  # in the last 7 runs/days from the recent run.
  num_runs_in_change_point_window: 7


test_2:
  test_name: apache_beam.testing.benchmarks.inference.pytorch_image_classification_benchmarks
  source: big_query
  metrics_dataset: beam_run_inference
  metrics_table: torch_inference_imagenet_results_resnet101
  project: apache-beam-testing
  metric_name: mean_load_model_latency_milli_secs
  labels:
    - perf-alert
    - run-inference
  min_runs_between_change_points: 5
    # the test runs once per day. So alert only if a perf regression lies
    # in the last 7 runs/days from the recent run.
  num_runs_in_change_point_window: 7
