name: Python Dependency Tests.

on:
  schedule:
    - cron: '10 2 * * *'
  pull_request:
    branches: ['master', 'release-*']
    tags: 'v*'
    paths: ['sdks/python/**']

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

python_dependency_tests:
  name: 'Python Dependency Tests'
  runs-on: ${{matrix.os}}
  strategy:
    fail-fast: false
    matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        params: [
          {"py_ver": "3.7", "py_env": "py37"},
          {"py_ver": "3.8", "py_env": "py38"},
          {"py_ver": "3.9", "py_env": "py39"},
          {"py_ver": "3.10", "py_env": "py310" },
          { "py_ver": "3.11", "py_env": "py311" },
        ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.params.py_ver }}
      - name: Install Build dependencies
        working-directory: ./sdks/python
        run: pip install -r build-requirements.txt
      - name: Install base_image_requirements.txt
        working-directory: ./sdks/python
        run: pip install --no-deps -r container/${{ matrix.params.py_env }}/base_image_requirements.txt
      - name: Install Apache Beam
        working-directory: ./sdks/python
        run: pip install --no-deps -v -e .[test,gcp,interactive,dataframe,aws,azure]
